version: "2"
linters:
  settings:
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
    lll:
      line-length: 100
    wsl:
      allow-cuddle-declarations: true
    revive:
      severity: "warning"
      confidence: 0.8

  enable:
    - asciicheck
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - goconst
    - godot
    - gosec
    - govet
    - iface
    - importas
    - ineffassign
    - lll
    - makezero
    - mirror
    - mnd
    - musttag
    - nestif
    - nilerr
    - prealloc
    - predeclared
    - protogetter
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - unused
    - wastedassign
    - whitespace
    - wsl
    - zerologlint

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - lll
          - gochecknoglobals
          - wsl
          - funlen
          - gomnd
          - dupl
