CREATE TABLE videos (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR NOT NULL,
    file_path VARCHAR NOT NULL,
    is_watched BOOLEAN DEFAULT FALSE,
    order_index TIMESTAMP UNIQUE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
