// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Video struct {
	ID         interface{} `json:"id"`
	Name       string      `json:"name"`
	Url        string      `json:"url"`
	FilePath   string      `json:"filePath"`
	IsWatched  *bool       `json:"isWatched"`
	OrderIndex *time.Time  `json:"orderIndex"`
	CreatedAt  *time.Time  `json:"createdAt"`
}
