// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Video struct {
	ID         int64      `json:"id"`
	Name       string     `json:"name"`
	Url        string     `json:"url"`
	Location   string     `json:"location"`
	IsWatched  *bool      `json:"isWatched"`
	OrderIndex *time.Time `json:"orderIndex"`
	CreatedAt  *time.Time `json:"createdAt"`
}
