// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const getVideos = `-- name: GetVideos :many
SELECT id, name, url, location, is_watched, order_index, created_at FROM videos ORDER BY order_index DESC
`

func (q *Queries) GetVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.query(ctx, q.getVideosStmt, getVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Location,
			&i.IsWatched,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
