// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
)

const addVideo = `-- name: AddVideo :one
INSERT INTO videos (name, url, location) values (?, ?, ?) RETURNING id, name, url, location, is_watched, order_index, created_at
`

type AddVideoParams struct {
	Name     string `json:"name"`
	Url      string `json:"url"`
	Location string `json:"location"`
}

func (q *Queries) AddVideo(ctx context.Context, arg AddVideoParams) (Video, error) {
	row := q.queryRow(ctx, q.addVideoStmt, addVideo, arg.Name, arg.Url, arg.Location)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Location,
		&i.IsWatched,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos WHERE id = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteVideoStmt, deleteVideo, id)
	return err
}

const getVideos = `-- name: GetVideos :many
SELECT id, name, url, location, is_watched, order_index, created_at FROM videos ORDER BY order_index DESC
`

func (q *Queries) GetVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.query(ctx, q.getVideosStmt, getVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Location,
			&i.IsWatched,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleWatchedStatus = `-- name: ToggleWatchedStatus :one
UPDATE videos SET is_watched = not is_watched WHERE id = ? RETURNING id, name, url, location, is_watched, order_index, created_at
`

func (q *Queries) ToggleWatchedStatus(ctx context.Context, id int64) (Video, error) {
	row := q.queryRow(ctx, q.toggleWatchedStatusStmt, toggleWatchedStatus, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Location,
		&i.IsWatched,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}
